spring:
  datasource:
    
    url: jdbc:mysql://172.16.64.6:3306/modeloGeneralFisi
    username: root
    password: desarrollo21
  jpa:
    hibernate:
     naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        strategy: org.hibernate.cfg.EJB3NamingStrategy
     ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect    
server:
  port: 8080
