spring:
  datasource:

    url: jdbc:mysql://127.0.0.1/modeloGeneralFisi
    username: root
    password:
  jpa:
    hibernate:
     naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        strategy: org.hibernate.cfg.EJB3NamingStrategy
     ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080
