spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/modelogeneralfisi
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
    
